### ISSUE TITLE
Add a markdown formatter for development

### ISSUE THREAD

**Issue by nathanjmcdougall** [usethis-python/usethis-python#366]
**Motivation**
Suggested via #349 

e.g.

```YAML
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.5.2
    hooks:
      - id: prettier
        types_or: [markdown]
```

**Summary of desired enhancement**
Add a markdown formatter; Prettier is [suggested ](https://learn.scientific-python.org/development/guides/style/#PC180) by `sp-repo-review`
