### ISSUE TITLE
Implement `usethis tool pydantic`

### ISSUE THREAD

**Issue by nathanjmcdougall** [usethis-python/usethis-python#374]
**Motivation**
It's simple to install but subtle to configure with type checkers and linters since it does some unusual things under the hood. For example, with the `TC` rule codes;

```TOML
[tool.ruff.lint.flake8-type-checking]
runtime-evaluated-base-classes = ["pydantic.BaseModel"]
```

**Summary of desired enhancement**
Add support for `pydantic` config in a way that integrates well with other tools.
